CREATE DATABASE CCXI;
-- CCXI stands for Code Cricket XI
USE CCXI;

-- Users table: Stores information about users who have accounts on CCXI (Code Cricket XI).
CREATE TABLE Users (
    user_id INT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(20) NOT NULL,
    join_date DATE NOT NULL,
    last_login DATETIME
);

-- Leagues table: Contains details about cricket leagues, including their names, start and end dates, and status.
CREATE TABLE Leagues (
    league_id INT PRIMARY KEY,
    league_name VARCHAR(70) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(20) NOT NULL
);

-- Teams table: Represents cricket teams participating in leagues, with details like team name, home ground, and coaches.
CREATE TABLE Teams (
    team_id INT PRIMARY KEY,
    team_name VARCHAR(50) NOT NULL,
    league_id INT,
    home_ground VARCHAR(180),
    head_coach VARCHAR(50),
    batting_coach VARCHAR(50),
    bowling_coach VARCHAR(50),
    fielding_coach VARCHAR(50),
    FOREIGN KEY (league_id) REFERENCES Leagues(league_id)
);

-- Players table: Stores information about cricket players, including their playing position, batting and bowling styles, and nationality.
CREATE TABLE Players (
    player_id INT PRIMARY KEY,
    player_name VARCHAR(55) NOT NULL,
    team_id INT,
    position VARCHAR(50),
    batting_style VARCHAR(40),
    bowling_style VARCHAR(40),
    nationality VARCHAR(50),
	is_captain BOOLEAN DEFAULT false,  -- To indicate that a player is not a captain unless explicitly set to "true".
    FOREIGN KEY (team_id) REFERENCES Teams(team_id)
);

-- Matches table: Contains details about cricket matches, including the teams playing, venue, date, and match result.
CREATE TABLE Matches (
    match_id INT PRIMARY KEY,
    league_id INT,
    team1_id INT,
    team2_id INT,
    match_date DATE,
    venue VARCHAR(100),
    result VARCHAR(50),
    home_ground VARCHAR(180),
    league_name VARCHAR(100),
    FOREIGN KEY (league_id) REFERENCES Leagues(league_id),
    FOREIGN KEY (team1_id) REFERENCES Teams(team_id),
    FOREIGN KEY (team2_id) REFERENCES Teams(team_id)
);

-- BattingRecords table: Records detailed batting performance statistics for each player in the tournament.
CREATE TABLE BattingRecords (
    batting_record_id INT PRIMARY KEY AUTO_INCREMENT, -- to ensure each record has a unique identifier, which is automatically generated by the database. This makes it easier to manage and reference individual batting records, as they each have a distinct assigned primary key. 
    player_id INT,
    league_id INT,
    total_matches_played INT,
    total_innings_played INT,
    total_tournament_runs INT,
    highest_score VARCHAR(10),
    average DECIMAL(5,2),
    strike_rate DECIMAL(5,2),
    hundreds INT,
    fifties INT,
    ducks INT,
    fours INT,
    sixes INT,
    FOREIGN KEY (player_id) REFERENCES Players(player_id),
    FOREIGN KEY (league_id) REFERENCES Leagues(league_id)
);

-- BowlingRecords table: Records detailed bowling performance statistics for each player in the tournament.
CREATE TABLE BowlingRecords (
    bowling_record_id INT PRIMARY KEY AUTO_INCREMENT,
    player_id INT,
    league_id INT,
    total_matches_played INT,
    total_innings_played INT,
    overs DECIMAL(5,2),
    maidens INT,
    runs INT,
    wickets INT,
    average DECIMAL(5,2),
    economy DECIMAL(5,2),
    strike_rate DECIMAL(5,2),
    FOREIGN KEY (player_id) REFERENCES Players(player_id),
    FOREIGN KEY (league_id) REFERENCES Leagues(league_id)
);

-- User_Predictions table: Stores predictions made by users about match outcomes.
CREATE TABLE User_Predictions (
    prediction_id INT PRIMARY KEY,
    user_id INT,
    match_id INT,
    predicted_winner VARCHAR(100),
    prediction_date DATE,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (match_id) REFERENCES Matches(match_id)
);

-- User_FavouriteTeams table: Stores information about which teams are marked as favorite by each user.
CREATE TABLE User_FavouriteTeams (
    favourite_id INT PRIMARY KEY,
    user_id INT,
    team_id INT,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (team_id) REFERENCES Teams(team_id)
);

INSERT INTO Users (user_id, username, email, password, join_date, last_login) VALUES
(1, 'johndoe', 'johndoe@example.com', 'pass123', '2023-01-15', '2024-05-01 14:23:00'),
(2, 'janedoe', 'janedoe@example.com', 'word456', '2023-02-20', '2024-05-02 09:15:00'),
(3, 'bobsaget', 'bobsaget@example.com', '123word', '2023-03-05', '2024-05-01 18:45:00'),
(4, 'alicew', 'alicew@example.com', 'alice789', '2023-04-10', '2024-05-03 11:25:00'),
(5, 'charliek', 'charliek@example.com', 'charlie000', '2023-05-25', '2024-05-01 22:30:00'),
(6, 'dianad', 'dianad@example.com', 'diana!23', '2023-06-12', '2024-05-02 13:45:00'),
(7, 'edwardr', 'edwardr@example.com', 'edward$99', '2023-07-18', '2024-05-01 07:10:00'),
(8, 'frankm', 'frankm@example.com', 'frankM56', '2023-08-22', '2024-05-03 15:50:00'),
(9, 'ginag', 'ginag@example.com', 'gina456', '2023-09-30', '2024-05-02 12:20:00'),
(10, 'harryp', 'harryp@example.com', 'harry789', '2023-10-05', '2024-05-01 10:05:00');

INSERT INTO Leagues (league_id, league_name, start_date, end_date, status) VALUES
(1, 'Pakistan Super League', '2024-01-15', '2024-02-25', 'completed'),
(2, 'Indian Premier League', '2024-03-25', '2024-05-10', 'ongoing'),
(3, 'Big Bash League', '2024-11-01', '2024-12-20', 'upcoming');

INSERT INTO Teams (team_id, team_name, league_id, home_ground, head_coach, batting_coach, bowling_coach, fielding_coach) VALUES
-- PSL Teams
(1, 'Lahore Qalandars', 1, 'Gaddafi Stadium', 'Aqib Javed', 'Mansoor Rana', 'Waqas Ahmed', 'Shahzad Butt'),
(2, 'Karachi Kings', 1, 'National Stadium', 'Phil Simmons', 'Ravi Bopara', 'Steven Kirby', 'Mohammad Mansoor'),
(3, 'Islamabad United', 1, 'Rawalpindi Cricket Stadium', 'Mike Hesson', 'Ashley Wright', 'James Franklin', 'Simon Helmot'),
(4, 'Multan Sultans', 1, 'Multan Cricket Stadium', 'Abdul Rehman', 'Alex Hartley', 'Catherine Dalton', 'Drikus Saaiman'),
-- IPL Teams
(5, 'Royal Challengers Bengaluru', 2, 'M. Chinnaswamy Stadium', 'Andy Flower', 'Adam Griffith', 'Sridharan Sriram', 'Malolan Rangarajan'),
(6, 'Chennai Super Kings', 2, 'M. A. Chidambaram Stadium', 'Stephen Fleming', 'Michael Hussey', 'Dwayne Bravo', 'Rajiv Kumar'),
(7, 'Mumbai Indians', 2, 'Wankhede Stadium', 'Mark Boucher', 'Kieron Pollard', 'Shane Bond', 'James Pamment'),
(8, 'Lucknow Super Giants', 2, 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'Justin Langer', 'Warren Andrews', 'Pravin Tambe', 'Jonty Rhodes'),
-- BBL Teams
(9, 'Perth Scorchers', 3, 'Optus Stadium', 'Adam Voges', 'Adam Voges', 'Tim Macdonald', 'Beau Casson'),
(10, 'Brisbane Heat', 3, 'The Gabba', 'Johan Botha', 'Darren Lehmann', 'Andy Bichel', 'Johan Botha'),
(11, 'Sydney Sixers', 3, 'Sydney Cricket Ground', 'Greg Shipperd', 'Greg Shipperd', 'Dan Christian', 'Dan Christian'),
(12, 'Adelaide Strikers', 3, 'Adelaide Oval', 'Jason Gillespie', 'Jason Gillespie', 'Tim Paine', 'Tim Paine');

INSERT INTO Players (player_id, player_name, team_id, position, batting_style, bowling_style, nationality, is_captain)
VALUES
-- Lahore Qalandars
(1, 'Abdullah Shafique', 1, 'Opening Batter', 'Right hand Bat', 'Right arm Offbreak', 'Pakistan', false),
(2, 'Fakhar Zaman', 1, 'Opening Batter', 'Left hand Bat', 'Slow Left arm Orthodox', 'Pakistan', false),
(3, 'Shai Hope', 1, 'Wicketkeeper Batter', 'Right hand Bat', NULL, 'West Indies', false),
(4, 'Rassie van der Dussen', 1, 'Top order Batter', 'Right hand Bat', 'Legbreak', 'South Africa', false),
(5, 'George Linde', 1, 'Allrounder', 'Left hand Bat', 'Slow Left arm Orthodox', 'South Africa', false),
(6, 'Rashid Khan', 1, 'Bowling Allrounder', 'Right hand Bat', 'Legbreak Googly', 'Afghanistan', false),
(7, 'Sikandar Raza', 1, 'Batting Allrounder', 'Right hand Bat', 'Right arm Offbreak, Legbreak', 'Zimbabwe', false),
(8, 'David Wiese', 1, 'Allrounder', 'Right hand Bat', 'Right arm Medium fast', 'Namibia', false),
(9, 'Haris Rauf', 1, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'Pakistan', false),
(10, 'Shaheen Shah Afridi', 1, 'Bowler', 'Left hand Bat', 'Left arm Fast', 'Pakistan', true),
(11, 'Zaman Khan', 1, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'Pakistan', false),
-- Karachi Kings: 2
(12, 'Irfan Khan', 2, 'Middle order Batter', 'Right hand Bat', 'Right arm Medium fast', 'Pakistan', false),
(13, 'Tim Seifert', 2, 'Wicketkeeper Batter', 'Right hand Bat', NULL, 'New Zealand', false),
(14, 'Shan Masood', 2, 'Opening Batter', 'Left hand Bat', 'Right arm Medium fast', 'Pakistan', true),
(15, 'James Vince', 2, 'Batter', 'Right hand Bat', 'Right arm Medium', 'England', false),
(16, 'Mohammad Nawaz', 2, 'Allrounder', 'Left hand Bat', 'Slow Left arm Orthodox', 'Pakistan', false),
(17, 'Kieron Pollard', 2, 'Batting Allrounder', 'Right hand Bat', 'Right arm Medium', 'West Indies', false),
(18, 'Daniel Sams', 2, 'Allrounder', 'Right hand Bat', 'Left arm Fast medium', 'Australia', false),
(19, 'Shoaib Malik', 2, 'Allrounder', 'Right hand Bat', 'Right arm Offbreak', 'Pakistan', false),
(20, 'Anwar Ali', 2, 'Bowler', 'Right hand Bat', 'Right arm Medium fast', 'Pakistan', false),
(21, 'Hasan Ali', 2, 'Bowler', 'Right hand Bat', 'Right arm Medium fast', 'Pakistan', false),
(22, 'Tabraiz Shamsi', 2, 'Bowler', 'Right hand Bat', 'Left arm Wrist spin', 'South Africa', false),
-- Islamabad United: 3
(23, 'Azam Khan', 3, 'Wicketkeeper Batter', 'Right hand Bat', NULL, 'Pakistan', false),
(24, 'Alex Hales', 3, 'Opening Batter', 'Right hand Bat', 'Right arm Medium', 'England', false),
(25, 'Colin Munro', 3, 'Opening Batter', 'Left hand Bat', 'Right arm Medium fast', 'New Zealand', false),
(26, 'Agha Salman', 3, 'Allrounder', 'Right hand Bat', 'Right arm Offbreak', 'Pakistan', false),
(27, 'Tom Curran', 3, 'Allrounder', 'Right hand Bat', 'Right arm Fast medium', 'England', false),
(28, 'Faheem Ashraf', 3, 'Bowling Allrounder', 'Left hand Bat', 'Right arm Medium', 'Pakistan', false),
(29, 'Imad Wasim', 3, 'Allrounder', 'Left hand Bat', 'Slow Left arm Orthodox', 'Pakistan', false),
(30, 'Shadab Khan', 3, 'Allrounder', 'Right hand Bat', 'Legbreak', 'Pakistan', true),
(31, 'Hunain Shah', 3, 'Bowler', 'Right hand Bat', 'Right arm Medium', 'Pakistan', false),
(32, 'Tymal Mills', 3, 'Bowler', 'Right hand Bat', 'Left arm Fast', 'England', false),
(33, 'Naseem Shah', 3, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'Pakistan', false),
-- Multan Sultans: 4
(34, 'Johnson Charles', 4, 'Wicketkeeper Batter', 'Right hand Bat', NULL, 'West Indies', false),
(35, 'Iftikhar Ahmed', 4, 'Middle order Batter', 'Right hand Bat', 'Right arm Offbreak', 'Pakistan', false),
(36, 'Khushdil Shah', 4, 'Middle order Batter', 'Left hand Bat', 'Slow Left arm Orthodox', 'Pakistan', false),
(37, 'Dawid Malan', 4, 'Top order Batter', 'Left hand Bat', 'Legbreak', 'England', false),
(38, 'Mohammad Rizwan', 4, 'Wicketkeeper Batter', 'Right hand Bat', 'Right arm Medium', 'Pakistan', true),
(39, 'David Willey', 4, 'Bowling Allrounder', 'Left hand Bat', 'Left arm Fast medium', 'England', false),
(40, 'Abbas Afridi', 4, 'Bowler', 'Right hand Bat', 'Right arm Medium fast', 'Pakistan', false),
(41, 'Chris Jordan', 4, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'England', false),
(42, 'Shahnawaz Dahani', 4, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'Pakistan', false),
(43, 'Reece Topley', 4, 'Bowler', 'Right hand Bat', 'Left arm Fast medium', 'England', false),
(44, 'Usama Mir', 4, 'Bowler', 'Right hand Bat', 'Legbreak', 'Pakistan', false),
-- Chennai Super Kings: 5, Royal Challengers Bangalore: 6, Mumbai Indians: 7, Lucknow Super Giants: 8
-- Chennai Super Kings: 5
(45, 'Ruturaj Gaikwad', 5, 'Batter', 'Right hand Bat', 'Right arm Offbreak', 'India', true),
(46, 'MS Dhoni', 5, 'Wicketkeeper Batter', 'Right hand Bat', 'Right arm Medium', 'India', false),
(47, 'Ajinkya Rahane', 5, 'Top order Batter', 'Right hand Bat', 'Right arm Medium', 'India', false),
(48, 'Moeen Ali', 5, 'Batting Allrounder', 'Left hand Bat', 'Right arm Offbreak', 'England', false),
(49, 'Ravindra Jadeja', 5, 'Allrounder', 'Left hand Bat', 'Slow Left arm Orthodox', 'India', false),
(50, 'Daryl Mitchell', 5, 'Batting Allrounder', 'Right hand Bat', 'Right arm Medium', 'New Zealand', false),
(51, 'Mitchell Santner', 5, 'Bowling Allrounder', 'Left hand Bat', 'Slow Left arm Orthodox', 'New Zealand', false),
(52, 'Deepak Chahar', 5, 'Bowler', 'Right hand Bat', 'Right arm Medium', 'India', false),
(53, 'Richard Gleeson', 5, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'England', false),
(54, 'Simarjeet Singh', 5, 'Bowler', 'Right hand Bat', 'Right arm Medium fast', 'India', false),
(55, 'Maheesh Theekshana', 5, 'Bowler', 'Right hand Bat', 'Right arm Offbreak', 'India', false),
-- Royal Challengers Bangalore: 6
(56, 'Faf du Plessis', 6, 'Middle order Batter', 'Right hand Bat', 'Legbreak', 'South Africa', true),
(57, 'Saurav Chauhan', 6, 'Top order Batter', 'Left hand Bat', 'Right arm Offbreak', 'India', false),
(58, 'Virat Kohli', 6, 'Top order Batter', 'Right hand Bat', 'Right arm Medium', 'India', false),
(59, 'Tom Curran', 6, 'Allrounder', 'Right hand Bat', 'Right arm Fast medium', 'England', false),
(60, 'Cameron Green', 6, 'Batting Allrounder', 'Right hand Bat', 'Right arm Fast medium', 'Australia', false),
(61, 'Will Jacks', 6, 'Batting Allrounder', 'Right hand Bat', 'Right arm Offbreak', 'England', false),
(62, 'Glenn Maxwell', 6, 'Batting Allrounder', 'Right hand Bat', 'Right arm Offbreak', 'Australia', false),
(63, 'Lockie Ferguson', 6, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'New Zealand', false),
(64, 'Alzarri Joseph', 6, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'West Indies', false),
(65, 'Reece Topley', 6, 'Bowler', 'Right hand Bat', 'Left arm Fast medium', 'England', false),
(66, 'Vijaykumar Vyshak', 6, 'Bowler', 'Right hand Bat', 'Right arm Medium', 'India', false),
-- Mumbai Indians: 7
(67, 'Tim David', 7, 'Middle order Batter', 'Right hand Bat', 'Right arm Offbreak', 'Australia', false),
(68, 'Ishan Kishan', 7, 'Wicketkeeper Batter', 'Left hand Bat', NULL, 'India', false),
(69, 'Rohit Sharma', 7, 'Top order Batter', 'Right hand Bat', 'Right arm Offbreak', 'India', false),
(70, 'Suryakumar Yadav', 7, 'Batter', 'Right hand Bat', 'Right arm Medium, Right arm Offbreak', 'India', false),
(71, 'Hardik Pandya', 7, 'Allrounder', 'Right hand Bat', 'Right arm Medium fast', 'India', true),
(72, 'Dewald Brevis', 7, 'Batting Allrounder', 'Right hand Bat', 'Legbreak', 'South Africa', false),
(73, 'Shreyas Gopal', 7, 'Allrounder', 'Right hand Bat', 'Legbreak', 'India', false),
(74, 'Mohammad Nabi', 7, 'Allrounder', 'Right hand Bat', 'Right arm Offbreak', 'Afghanistan', false),
(75, 'Romario Shepherd', 7, 'Bowling Allrounder', 'Right hand Bat', 'Right arm Fast medium', 'West Indies', false),
(76, 'Jasprit Bumrah', 7, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'India', false),
(77, 'Gerald Coetzee', 7, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'South Africa', false),
-- Lucknow Super Giants: 8
(78, 'KL Rahul', 8, 'Wicketkeeper Batter', 'Right hand Bat', NULL, 'India', true),
(79, 'Quinton de Kock', 8, 'Wicketkeeper Batter', 'Left hand Bat', NULL, 'South Africa', false),
(80, 'Nicholas Pooran', 8, 'Wicketkeeper Batter', 'Left hand Bat', 'Right arm Offbreak', 'West Indies', false),
(81, 'Ashton Turner', 8, 'Middle order Batter', 'Right hand Bat', 'Right arm Offbreak', 'Australia', false),
(82, 'Kyle Mayers', 8, 'Batting Allrounder', 'Left hand Bat', 'Right arm Medium', 'West Indies', false),
(83, 'Marcus Stoinis', 8, 'Batting Allrounder', 'Right hand Bat', 'Right arm Medium', 'Australia', false),
(84, 'David Willey', 8, 'Bowling Allrounder', 'Left hand Bat', 'Left arm Fast medium', 'England', false),
(85, 'Matt Henry', 8, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'New Zealand', false),
(86, 'Shamar Joseph', 8, 'Bowler', 'Left hand Bat', 'Right arm Fast', 'West Indies', false),
(87, 'Mayank Yadav', 8, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'India', false),
(88, 'Yash Thakur', 8, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'India', false), 
-- Perth Scorchers: 9, Brisbane Heat: 10, Sydney Sixers: 11, Adelaide Strikers: 12
-- Perth Scorchers: 9
(89, 'Cooper Connolly', 9, 'Top order Batter', 'Left hand Bat', 'Slow Left arm Orthodox', 'Australia', false),
(90, 'Zak Crawley', 9, 'Top order Batter', 'Right hand Bat', 'Right arm Offbreak', 'England', false),
(91, 'Stephen Eskinazi', 9, 'Middle order Batter', 'Right hand Bat', NULL, 'Australia', false),
(92, 'Laurie Evans', 9, 'Batter', 'Right hand Bat', 'Right arm Offbreak', 'England', false),
(93, 'Aaron Hardie', 9, 'Allrounder', 'Right hand Bat', 'Right arm Medium fast', 'Australia', true),
(94, 'Mitchell Marsh', 9, 'Allrounder', 'Right hand Bat', 'Right arm Medium', 'Australia', false),
(95, 'Ashton Agar', 9, 'Bowler', 'Left hand Bat', 'Slow Left arm Orthodox', 'Australia', false),
(96, 'Jason Behrendorff', 9, 'Bowler', 'Right hand Bat', 'Left arm Fast medium', 'Australia', false),
(97, 'Matthew Kelly', 9, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'Australia', false),
(98, 'Lance Morris', 9, 'Bowler', 'Right hand Bat', 'Right arm Fast', 'Australia', false),
(99, 'Andrew Tye', 9, 'Bowler', 'Right hand Bat', 'Right arm Medium fast', 'Australia', false),
-- Brisbane Heat: 10
(100, 'Sam Billings', 10, 'Wicketkeeper Batter', 'Right hand Bat', NULL, 'England', false),
(101, 'Usman Khawaja', 10, 'Top order Batter', 'Left hand Bat', 'Right arm Medium', 'Australia', false),
(102, 'Marnus Labuschagne', 10, 'Batter', 'Right hand Bat', 'Legbreak', 'Australia', false),
(103, 'Colin Munro', 10, 'Opening Batter', 'Left hand Bat', 'Right arm Medium fast', 'New Zealand', false),
(104, 'Jimmy Peirson', 10, 'Wicketkeeper', 'Right hand Bat', NULL, 'Australia', false),
(105, 'Charlie Wakim', 10, 'Top order Batter', 'Right hand Bat', NULL, 'Australia', false),
(106, 'Nathan McSweeney', 10, 'Allrounder', 'Right hand Bat', 'Right arm Offbreak', 'Australia', true),
(107, 'Michael Neser', 10, 'Bowling Allrounder', 'Right hand Bat', 'Right arm Medium fast', 'Australia', false),
(108, 'Paul Walter', 10, 'Allrounder', 'Left hand Bat', 'Left arm Medium', 'England', false),
(109, 'Xavier Bartlett', 10, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'Australia', false),
(110, 'Spencer Johnson', 10, 'Bowler', 'Left hand Bat', 'Left arm Fast', 'Australia', false),
-- Sydney Sixers: 11
(111, 'Jack Edwards', 11, 'Batter', 'Right hand Bat', 'Right arm Medium', 'Australia', false),
(112, 'Kurtis Patterson', 11, 'Middle order Batter', 'Left hand Bat', 'Right arm Offbreak', 'Australia', false),
(113, 'Josh Philippe', 11, 'Wicketkeeper Batter', 'Right hand Bat', NULL, 'Australia', false),
(114, 'Steven Smith', 11, 'Top order Batter', 'Right hand Bat', 'Legbreak Googly', 'Australia', false),
(115, 'James Vince', 11, 'Batter', 'Right hand Bat', 'Right arm Medium', 'England', false),
(116, 'Sean Abbott', 11, 'Bowling Allrounder', 'Right hand Bat', 'Right arm Fast medium', 'Australia', false),
(117, 'Tom Curran', 11, 'Allrounder', 'Right hand Bat', 'Right arm Fast medium', 'England', false),
(118, 'Moises Henriques', 11, 'Allrounder', 'Right hand Bat', 'Right arm Fast medium', 'Australia', true),
(119, 'Ben Dwarshuis', 11, 'Bowler', 'Left hand Bat', 'Left arm Fast medium', 'Australia', false),
(120, 'Izharulhaq Naveed', 11, 'Bowler', 'Right hand Bat', 'Legbreak', 'Afghanistan', false),
(121, 'Jackson Bird', 11, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'Australia', false),
-- Adelaide Strikers: 12
(122, 'Alex Carey', 12, 'Wicketkeeper Batter', 'Left hand Bat', NULL, 'Australia', false),
(123, 'Travis Head', 12, 'Top order Batter', 'Left hand Bat', 'Right arm Offbreak', 'Australia', false),
(124, 'Adam Hose', 12, 'Middle order Batter', 'Right hand Bat', 'Right arm Medium fast', 'England', false),
(125, 'Chris Lynn', 12, 'Batter', 'Right hand Bat', 'Slow Left arm Orthodox', 'Australia', false),
(126, 'Matthew Short', 12, 'Top order Batter', 'Right hand Bat', 'Right arm Offbreak', 'Australia', true),
(127, 'D Arcy Short', 12, 'Opening Batter', 'Left hand Bat', 'Left arm Wrist spin', 'Australia', false),
(128, 'Jamie Overton', 12, 'Bowling Allrounder', 'Right hand Bat', 'Right arm Fast', 'England', false),
(129, 'Cameron Boyce', 12, 'Bowler', 'Right hand Bat', 'Legbreak', 'Australia', false),
(130, 'Brendan Doggett', 12, 'Bowler', 'Right hand Bat', 'Right arm Fast medium', 'Australia', false),
(131, 'Ben Manenti', 12, 'Bowler', 'Right hand Bat', 'Right arm Offbreak', 'Australia', false),
(132, 'David Payne', 12, 'Bowler', 'Right hand Bat', 'Left arm Fast medium', 'England', false);

-- To find out all teams have exactly "11" players.
SELECT t.team_name, COUNT(p.player_id) AS num_players
FROM Teams t
LEFT JOIN Players p ON t.team_id = p.team_id
GROUP BY t.team_name
HAVING COUNT(p.player_id) <> 11;
-- This query gives a list of teams that do not have exactly 11 players. 
-- If a team is missing players or has more than 11 players, it will be shown in the result. 
-- If a team has exactly 11 players, it will not be included in the result.

-- To find out the playing XI for any team. "Change t.team_name" to the team you want.
SELECT p.player_name
FROM Players p
JOIN Teams t ON p.team_id = t.team_id
WHERE t.team_name = 'Brisbane Heat';

